import React from 'react';
import { ArrowRight } from 'lucide-react';
import { BATCH_COOKING_GUIDE as guide } from '../../content/seoFoodCostGuides';
import { BATCH_COOKING_DISCLOSURE_FOOTER, BATCH_COOKING_DISCLOSURES } from '../../content/programmaticDisclosures';
import { ProgrammaticDisclosureFooter, ProgrammaticDisclosureList } from '../ProgrammaticDisclosures';

const Section: React.FC<{ title: string; children: React.ReactNode; className?: string }> = ({ title, children, className = '' }) => <section className={`mt-10 ${className}`}><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-dbd-ink-3">{children}</div></section>;
const List: React.FC<{ children: React.ReactNode }> = ({ children }) => <ul className="space-y-3">{children}</ul>;
const Item: React.FC<{ children: React.ReactNode }> = ({ children }) => <li className="flex gap-3"><span aria-hidden="true" className="text-dbd-accent">—</span><span>{children}</span></li>;
const InternalLink: React.FC<{ href: string; children: React.ReactNode }> = ({ href, children }) => <a href={href} className="font-semibold text-dbd-accent hover:underline">{children}</a>;
const SourceLink: React.FC<{ href: string; children: React.ReactNode }> = ({ href, children }) => <a href={href} target="_blank" rel="noreferrer" className="font-semibold text-dbd-accent hover:underline">{children}</a>;

export const BatchCookingGuideView: React.FC<{ onPlanWeek: () => void }> = ({ onPlanWeek }) => (
  <div className="min-h-screen bg-[#faf9f7] text-dbd-ink">
    <header className="border-b border-dbd-rule/50 bg-dbd-surface"><div className="mx-auto flex min-h-[82px] max-w-5xl items-center justify-between px-4 sm:min-h-[96px]"><a href="/" aria-label="DinnerByDesign home"><img src="/dbd-logo-with-pin.png" alt="DinnerByDesign" className="h-[38px] w-auto max-w-[230px] object-contain mix-blend-multiply sm:h-[44px]" /></a><a href="/signin?mode=signin" className="text-xs font-bold text-dbd-accent hover:underline">Sign in</a></div></header>
    <main className="mx-auto max-w-3xl px-4 py-8 pb-20 sm:py-12">
      <nav aria-label="Breadcrumb" className="text-xs text-dbd-ink-3"><a href="/" className="hover:underline">DinnerByDesign</a><span className="px-2">/</span><span>Food cost guides</span></nav>
      <article>
        <header className="mt-7"><p className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-dbd-accent">Food cost guide</p><h1 className="mt-2 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{guide.title}</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-dbd-ink-3">{guide.description}</p><p className="mt-3 text-xs text-dbd-ink-3">By {guide.editorialOwner} · Published 21 July 2026 · Last reviewed 21 July 2026</p></header>
        <Section title="Quick answer" className="border-t border-dbd-rule/50 pt-8"><p>Batch cooking can reduce what you spend on food, but quantity alone does not create a saving. Cooking a very large amount only helps if the portions are suitable, someone actually wants to eat them again, and the extra does not just disappear into the freezer. The saving comes from how the batch is planned and used, not from the size of the pot. A large batch cooked without a plan for every portion can end up costing more than cooking smaller amounts more often.</p></Section>
        <Section title="Where the economies come from"><List><Item>Using complete packs of ingredients more effectively, rather than buying more than one dinner needs and using only part of it.</Item><Item>Buying fewer small or partially used packs across the week, since one larger cook can draw on a single set of ingredients.</Item><Item>Spreading preparation across several dinners, so chopping, browning or making a sauce base happens once.</Item><Item>Making planned use of leftovers, rather than leaving them to go off unnoticed.</Item><Item>Reducing reliance on expensive last-minute options — a takeaway or convenience dinner bought because nothing else was ready.</Item><Item>Portioning food before serving or freezing, which helps prevent oversized servings and forgotten containers.</Item><Item>Reusing one cooked base in different ways, so variety does not depend on buying new ingredients each time.</Item></List></Section>
        <Section title="What makes a good batch-cooked dish"><p>Not every dish is worth cooking in bulk. A good candidate stores well without separating or turning watery, divides easily into individual portions, reheats successfully without drying out or losing texture, and still tastes appealing on the third or fourth time round, not just the first. Dishes built around a sauce, stew or braise tend to fit this better than anything meant to be served freshly assembled, such as a salad or a dish that relies on a just-cooked crisp texture.</p></Section>
        <Section title="Batch cooking does not have to mean repetition"><p>The dinner that gets tiresome is usually the one eaten in exactly the same form four times in a row. The more useful approach is to batch-cook a base — a sauce, a cooked protein, a pot of roasted vegetables — and finish it differently each time with a different grain, spice, vegetable or side. The cooking happens once; what you eat still changes.</p></Section>
        <Section title="Useful batch-cooking bases"><List><Item>Tomato and vegetable sauce</Item><Item>Cooked mince and vegetables</Item><Item>Lentil and tomato base</Item><Item>Roasted vegetables</Item><Item>Bean or chickpea stew</Item><Item>Cooked chicken, prepared plainly so it can go in different directions — refrigerate portions you will use within a day or two, and freeze the rest</Item></List></Section>
        <Section title="Turning one base into different dinners"><p>A tomato-and-vegetable base is a good example of how far one batch can stretch. The same pot can become a herby pasta sauce one night, a smoky bean stew with tinned chickpeas or cannellini beans and a spoonful of smoked paprika another night, a gently spiced topping for a baked potato later in the week, or the sauce underneath a tray bake with whatever vegetables need using. The base does the work; a different grain, protein, spice or side changes what is actually on the plate.</p><p>A batch of cooked mince works the same way — stirred through pasta one night, spooned into a jacket potato or wrapped in a tortilla another, or added to rice with a different set of spices later in the week. A lentil and tomato base can move from a simple stew, to a sauce under a baked vegetable, to a filling alongside flatbread, without needing a fresh set of ingredients each time. If you plan to use a base later rather than within the next day or two, freeze the later portions and defrost them safely in the fridge rather than leaving them refrigerated for the whole week.</p></Section>
        <ProgrammaticDisclosureList items={BATCH_COOKING_DISCLOSURES.slice(0, 1)} className="mt-6" />
        <Section title="Portioning before storage"><p>Dividing a batch into individual or dinner-sized portions as soon as it is cool enough to store, rather than putting the whole pot straight into one large container, makes a real difference. It is much easier to take out exactly what a dinner needs, rather than defrosting more than you intend to eat because the portions are not already the right size. It also makes forgotten containers less likely, since a labelled, sensibly sized portion is easier to plan around than an anonymous large block.</p></Section>
        <Section title="Fridge and freezer planning"><p>Current Food Standards Agency guidance is to cool cooked food and refrigerate it within two hours, eat refrigerated leftovers within 48 hours or freeze them, and reheat food only once, until it is steaming hot all the way through. Freeze portions promptly once they have cooled, and label each one with the dish and date, so nothing sits unidentified at the back of the freezer until it is no longer worth eating.</p><p>Cooked rice needs particular care: cool it quickly, keep it refrigerated for no more than one day before reheating, reheat it only once, and make sure it is steaming hot throughout. If a batch of rice will not be used that quickly, freeze it promptly instead.</p></Section>
        <ProgrammaticDisclosureList items={BATCH_COOKING_DISCLOSURES.slice(1)} className="mt-6" />
        <Section title="When batch cooking can cost more"><List><Item>Overbuying ingredients because a recipe is being scaled up, rather than checking what the household will actually get through.</Item><Item>Adding too many special or one-off ingredients to a large batch, which increases the cost of the whole pot rather than just one dinner.</Item><Item>Freezing more than a household&apos;s freezer can reasonably hold well, leading to poor storage conditions or food pushed to the back and forgotten.</Item><Item>Preparing more portions than the household actually wants to eat, so some are thrown away rather than used.</Item></List><p>In each case, the batch itself is not the problem — the absence of a plan for every portion is.</p></Section>
        <Section title="Frequently asked questions">{guide.faqs.map(faq => <section key={faq.question}><h3 className="font-bold text-dbd-ink">{faq.question}</h3><p className="mt-2">{faq.answer}</p></section>)}</Section>
        <Section title="How DinnerByDesign can help"><p>Use the Batch-friendly filter to find dinners that suit cooking in bulk, and Plan my week to schedule how each portion will be used across the week — including which portions are eaten from the fridge in the next day or two, and which are frozen for later — rather than cooking a large batch without a plan for all of it. Shared-ingredient planning and the generated shopping list can help you buy complete packs with a specific use for all the ingredients, rather than ending up with a partially used ingredient left over.</p></Section>
        <Section title="Sources and further reading" className="border-t border-dbd-rule/50 pt-8"><ul className="space-y-3 text-sm leading-6">{guide.sources.map(source => <li key={source.url}><SourceLink href={source.url}>{source.label}</SourceLink></li>)}</ul></Section>
        <Section title="Related guidance"><p><InternalLink href="/food-costs/portion-planning-and-food-waste">Plan portions and reduce food waste</InternalLink>, <InternalLink href="/food-costs/low-cost-cooking-techniques">explore low-cost cooking techniques</InternalLink>, <InternalLink href="/food-safety">review food-safety guidance</InternalLink> or <InternalLink href="/recipe-methodology">read how dinners are selected</InternalLink>.</p></Section>
      </article>
      <ProgrammaticDisclosureFooter copy={BATCH_COOKING_DISCLOSURE_FOOTER} className="mt-10" />
      <section className="mt-10 rounded bg-dbd-ink p-6 text-white sm:flex sm:items-center sm:justify-between sm:gap-6"><div><h2 className="text-xl font-bold">Plan every portion</h2><p className="mt-2 text-sm leading-6 text-white/70">Find batch-friendly dinners and decide how each portion will be used.</p></div><button type="button" onClick={onPlanWeek} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-white px-5 text-sm font-bold text-dbd-ink sm:mt-0 sm:w-auto">Plan my week <ArrowRight size={16} /></button></section>
    </main>
  </div>
);
