import React from 'react';
import { ArrowRight } from 'lucide-react';
import { GROCERY_COST_OPTIONS_GUIDE as guide, GROCERY_COST_STARTING_POINTS } from '../../content/groceryCostOptionsGuide';
import { GROCERY_COST_OPTIONS_DISCLOSURE_FOOTER, GROCERY_COST_OPTIONS_DISCLOSURES } from '../../content/programmaticDisclosures';
import { ProgrammaticDisclosureFooter, ProgrammaticDisclosureList } from '../ProgrammaticDisclosures';

const Section: React.FC<{ title: string; children: React.ReactNode; className?: string }> = ({ title, children, className = '' }) => <section className={`mt-10 ${className}`}><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-dbd-ink-3">{children}</div></section>;
const InternalLink: React.FC<{ href: string; children: React.ReactNode }> = ({ href, children }) => <a href={href} className="font-semibold text-dbd-accent hover:underline">{children}</a>;
const SourceLink: React.FC<{ href: string; children: React.ReactNode }> = ({ href, children }) => <a href={href} target="_blank" rel="noreferrer" className="font-semibold text-dbd-accent hover:underline">{children}</a>;

export const GroceryCostOptionsGuideView: React.FC<{ onPlanWeek: () => void }> = ({ onPlanWeek }) => (
  <div className="min-h-screen bg-[#faf9f7] text-dbd-ink">
    <header className="border-b border-dbd-rule/50 bg-dbd-surface"><div className="mx-auto flex min-h-[82px] max-w-5xl items-center justify-between px-4 sm:min-h-[96px]"><a href="/" aria-label="DinnerByDesign home"><img src="/dbd-logo-with-pin.png" alt="DinnerByDesign" className="h-[38px] w-auto max-w-[230px] object-contain mix-blend-multiply sm:h-[44px]" /></a><a href="/signin?mode=signin" className="text-xs font-bold text-dbd-accent hover:underline">Sign in</a></div></header>
    <main className="mx-auto max-w-3xl px-4 py-8 pb-20 sm:py-12">
      <nav aria-label="Breadcrumb" className="text-xs text-dbd-ink-3"><a href="/" className="hover:underline">DinnerByDesign</a><span className="px-2">/</span><a href="/guides" className="hover:underline">Guides</a><span className="px-2">/</span><span>Food cost guides</span></nav>
      <article>
        <header className="mt-7"><p className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-dbd-accent">Food cost guide</p><h1 className="mt-2 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{guide.title}</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-dbd-ink-3">{guide.description}</p><p className="mt-3 text-xs text-dbd-ink-3">By {guide.editorialOwner} · Published 21 July 2026 · Last reviewed 21 July 2026</p></header>
        <section className="mt-10 border-t border-dbd-rule/50 pt-8"><div className="space-y-4 text-[15px] leading-7 text-dbd-ink-3"><p>Controlling what you spend on groceries involves more than hunting for the cheapest products on the shelf. It is really about a handful of connected decisions: planning what you will actually cook, choosing realistic quantities, coordinating ingredients across several dinners, using complete packs effectively, avoiding unnecessary waste, and having a purpose for any surplus portions.</p><p>One distinction is worth keeping in mind throughout: the value of the ingredients you use in a dinner is not the same as the cost of the complete pack you had to buy to get them. Many of the techniques below work by closing that gap — making sure more of what you pay for actually gets eaten.</p></div></section>
        <ProgrammaticDisclosureList items={GROCERY_COST_OPTIONS_DISCLOSURES.slice(0, 1)} className="mt-6" />
        <Section title="Quick answer"><p className="italic">The most effective approach is usually a combination of realistic portion planning, coordinated ingredients, flexible lower-cost products and a clear purpose for everything you buy. No single technique works for every household. The best starting point depends on whether your main problem is waste, expensive ingredients, lack of time or unpredictable weekly spending.</p></Section>
        <Section title="1. Plan several dinners together"><p>Choosing three or four dinners at a time, built around a budget and a small set of shared ingredients, cuts down on the disconnected purchases that quietly push up a weekly shop. It is worth keeping this flexible rather than rigid — a plan that can absorb a changed evening or a swapped dinner is more useful than one that falls apart the first time your week does not go to schedule.</p><p>Our <InternalLink href="/food-costs/uk-food-costs-2026">guide to UK food costs</InternalLink> looks at where grocery spending typically goes in more detail, a sample plan like <InternalLink href="/dinner-plans/5-dinners-for-2-under-40">5 dinners for 2 under £40</InternalLink> shows what a coordinated, budget-led week can look like, and <InternalLink href="/food-costs/five-dinners-same-ingredients">five dinners using the same ingredients</InternalLink> demonstrates how one basket can still produce variety.</p></Section>
        <Section title="2. Plan realistic portions"><p>Portion planning is not about automatically serving less — it is about deciding how many people a dinner needs to serve, and what any extra portions are for. This matters at the checkout too: using only part of a pack does not reduce what you paid for it unless the rest gets used later, whether that is another dinner, a lunch, or the freezer.</p><p>Household size affects this more than anything else. Our guide to <InternalLink href="/food-costs/portion-planning-and-food-waste">portion planning and food waste</InternalLink> covers the general principles, and <InternalLink href="/food-costs/cooking-for-one-without-waste">cooking for one without waste</InternalLink> looks specifically at adjusting for a smaller household.</p></Section>
        <Section title="3. Batch-cook with a purpose"><p>Cooking a larger quantity only helps when every portion has somewhere to go: another dinner, the fridge for prompt use, the freezer for later, or a flexible base you can finish differently each time. Batch cooking without a plan for the extra is not a saving — it is just a bigger version of the same risk.</p><p>Our guide to <InternalLink href="/food-costs/batch-cooking-on-a-budget">batch cooking on a budget</InternalLink> looks at when it helps and when it does not.</p></Section>
        <Section title="4. Use lower-cost cooking techniques"><p>Stewing, braising, roasting, baking, and building a good sauce are all ways of turning modest ingredients into a dinner with real depth of flavour and texture. Herbs, spices and aromatics do a lot of the work here — budget-conscious cooking does not have to mean bland cooking. Our guide to <InternalLink href="/food-costs/low-cost-cooking-techniques">low-cost cooking techniques</InternalLink> goes through these in more detail.</p></Section>
        <Section title="5. Explore cuisines that use inexpensive staples well"><p>Several culinary traditions make good use of pulses, grains, tomatoes, vegetables, herbs and spices to build a satisfying dinner without leaning on an expensive centrepiece ingredient. No cuisine is inherently cheap — the cost still depends on the specific ingredients and products you choose — but the techniques are genuinely useful. Our <InternalLink href="/food-costs/mediterranean-inspired-affordable-cooking">Mediterranean-inspired affordable cooking guide</InternalLink> explores this in practice.</p></Section>
        <Section title="6. Consider lower-cost cuts and alternative proteins"><p>Lower-cost meat cuts, offal, eggs, and beans, chickpeas or lentils can all bring protein to a dinner without needing a large, expensive centrepiece. Combining a smaller amount of meat with vegetables, grains or pulses often works just as well as a bigger portion on its own. See our guides to <InternalLink href="/food-costs/cooking-for-four-with-lower-cost-cuts">cooking for four with lower-cost cuts</InternalLink> and <InternalLink href="/food-costs/cooking-with-offal-on-a-budget">cooking with offal on a budget</InternalLink> for more detail. The most economical option will depend on the products available, the pack sizes and what your household will genuinely use.</p></Section>
        <Section title="7. Decide when fresh or frozen is more practical"><p>Fresh and frozen each suit different dinners — shelf life, convenience, texture, preparation and how likely something is to go to waste all vary by ingredient and how you are planning to cook it. Neither format is always the better choice; it depends on how soon the ingredient will be used and how you intend to cook it. Our <InternalLink href="/food-costs/fresh-or-frozen">fresh or frozen guide</InternalLink> covers this in more detail.</p></Section>
        <Section title="8. Use seasonal and flexible dinner formats"><p>Stews, tray bakes, soups and adaptable sauces are naturally good at absorbing whatever vegetables are available, already in the fridge, or simply need using. <InternalLink href="/food-costs/summer-stews-seasonal-vegetables">Summer stews</InternalLink> are a good example of this — light, quick-cooking dinners that flex around what you have without feeling like an afterthought.</p></Section>
        <Section title="9. Give complete packs more than one purpose"><p>A single ingredient bought for one dinner can often do more than one job across the week. Peppers might go into a spiced rice dish, a stew and a tray bake; a tub of yoghurt into a sauce one night and a dressing another; a bag of spinach into a pasta dish and a curry-inspired dinner; a plainly cooked batch of chicken finished with a different set of flavours each time. This is not about building a rigid weekly menu. It is about noticing where one purchase can quietly cover several dinners. Our guide to <InternalLink href="/food-costs/how-to-use-complete-packs">using complete packs without wasting ingredients</InternalLink> shows how to plan those further uses before shopping.</p></Section>
        <Section title="10. Start with ingredients already available"><p>Before choosing what to cook, it is worth checking the cupboard, fridge and freezer first. Prioritise opened products and ingredients that need using soon, while continuing to follow use-by dates and storage instructions.</p></Section>
        <ProgrammaticDisclosureList items={GROCERY_COST_OPTIONS_DISCLOSURES.slice(1, 3)} className="mt-6" />
        <Section title="11. Keep flexible fallback dinners available"><p>A small collection of dependable dinners — built from eggs, rice, pasta, frozen vegetables, pulses or tinned tomatoes — reduces the chance of an expensive last-minute decision on a night when nothing has been planned. These do not have to be an afterthought: a well-seasoned baked egg dish or a good tomato pasta can be just as appetising as anything else in the week&apos;s plan.</p></Section>
        <Section title="12. Build the shopping list from scheduled dinners"><p>A shopping list that follows your dinner plan, rather than the other way around, naturally accounts for household servings, ingredients shared between dinners, complete pack sizes, and what is already available at home. This is where planning, portioning and pack awareness come together into one practical step, and it is the point where DinnerByDesign can help most directly — generating a shopping list from the dinners you have actually scheduled.</p></Section>
        <Section title="Where should you start?"><div className="overflow-x-auto rounded border border-dbd-rule/60 bg-white"><table className="w-full min-w-[620px] border-collapse text-left text-sm"><thead className="bg-dbd-surface-2 text-dbd-ink"><tr><th className="border-b border-dbd-rule/60 px-4 py-3 font-bold">If the main problem is...</th><th className="border-b border-dbd-rule/60 px-4 py-3 font-bold">A useful place to start</th></tr></thead><tbody>{GROCERY_COST_STARTING_POINTS.map(([problem, start]) => <tr key={problem} className="border-b border-dbd-rule/40 last:border-0"><th scope="row" className="px-4 py-3 font-semibold text-dbd-ink">{problem}</th><td className="px-4 py-3">{start}</td></tr>)}</tbody></table></div></Section>
        <Section title="Bringing it together"><p>These techniques work best in combination, and you do not need to adopt all twelve at once.</p><p className="italic">Portion planning becomes more useful when dinners share ingredients. Batch cooking works better when every portion has a purpose. Fresh and frozen choices become easier when the week is already planned. Choose the combination that gives your household greater control.</p></Section>
        <Section title="Frequently asked questions">{guide.faqs.map(faq => <section key={faq.question}><h3 className="font-bold text-dbd-ink">{faq.question}</h3><p className="mt-2">{faq.answer}</p></section>)}</Section>
        <Section title="Sources and further reading" className="border-t border-dbd-rule/50 pt-8"><ul className="space-y-3 text-sm leading-6">{guide.sources.map(source => <li key={source.url}><SourceLink href={source.url}>{source.label}</SourceLink></li>)}</ul></Section>
        <ProgrammaticDisclosureList items={GROCERY_COST_OPTIONS_DISCLOSURES.slice(3)} className="mt-6" />
      </article>
      <ProgrammaticDisclosureFooter copy={GROCERY_COST_OPTIONS_DISCLOSURE_FOOTER} className="mt-10" />
      <section className="mt-10 rounded bg-dbd-ink p-6 text-white sm:flex sm:items-center sm:justify-between sm:gap-6"><div><h2 className="text-xl font-bold">Put these ideas into practice</h2><p className="mt-2 text-sm leading-6 text-white/70">Build a week of dinners around your household, budget and available time, then generate a shopping list from the dinners you schedule.</p></div><button type="button" onClick={onPlanWeek} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-white px-5 text-sm font-bold text-dbd-ink sm:mt-0 sm:w-auto">Plan my week <ArrowRight size={16} /></button></section>
    </main>
  </div>
);
