import React from 'react';
import { ArrowRight } from 'lucide-react';
import { MEDITERRANEAN_AFFORDABLE_COOKING_GUIDE as guide } from '../../content/seoFoodCostGuides';
import {
  MEDITERRANEAN_DISCLOSURE_FOOTER,
  MEDITERRANEAN_PRODUCT_DISCLOSURES,
  MEDITERRANEAN_SOURCE_DISCLOSURES,
  MEDITERRANEAN_STORAGE_DISCLOSURES,
} from '../../content/programmaticDisclosures';
import { ProgrammaticDisclosureFooter, ProgrammaticDisclosureList } from '../ProgrammaticDisclosures';

const Section: React.FC<{ title: string; children: React.ReactNode; className?: string }> = ({ title, children, className = '' }) => (
  <section className={`mt-10 ${className}`}><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-dbd-ink-3">{children}</div></section>
);
const List: React.FC<{ children: React.ReactNode }> = ({ children }) => <ul className="space-y-3">{children}</ul>;
const Item: React.FC<{ children: React.ReactNode }> = ({ children }) => <li className="flex gap-3"><span aria-hidden="true" className="text-dbd-accent">—</span><span>{children}</span></li>;
const SourceLink: React.FC<{ href: string; children: React.ReactNode }> = ({ href, children }) => <a href={href} target="_blank" rel="noreferrer" className="font-semibold text-dbd-accent hover:underline">{children}</a>;

export const MediterraneanAffordableCookingGuideView: React.FC<{ onPlanWeek: () => void }> = ({ onPlanWeek }) => (
  <div className="min-h-screen bg-[#faf9f7] text-dbd-ink">
    <header className="border-b border-dbd-rule/50 bg-dbd-surface"><div className="mx-auto flex min-h-[82px] max-w-5xl items-center justify-between px-4 sm:min-h-[96px]"><a href="/" aria-label="DinnerByDesign home"><img src="/dbd-logo-with-pin.png" alt="DinnerByDesign" className="h-[34.2px] w-auto max-w-[207px] object-contain mix-blend-multiply sm:h-[39.6px]" /></a><a href="/signin?mode=signin" className="text-xs font-bold text-dbd-accent hover:underline">Sign in</a></div></header>
    <main className="mx-auto max-w-3xl px-4 py-8 pb-20 sm:py-12">
      <nav aria-label="Breadcrumb" className="text-xs text-dbd-ink-3"><a href="/" className="hover:underline">DinnerByDesign</a><span className="px-2">/</span><span>Food cost guides</span></nav>
      <article>
        <header className="mt-7"><p className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-dbd-accent">Food cost guide</p><h1 className="mt-2 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{guide.title}</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-dbd-ink-3">{guide.description}</p><p className="mt-3 text-xs text-dbd-ink-3">By {guide.editorialOwner} · Published 20 July 2026 · Last reviewed 20 July 2026</p></header>
        <section className="mt-8 border-y border-dbd-rule/50 py-6 text-[15px] leading-7 text-dbd-ink-3"><p>Beans, lentils, grains, vegetables and a handful of well-chosen flavourings turn up again and again across the Mediterranean's many different culinary traditions — and they're a genuinely useful starting point for a satisfying, affordable dinner. This isn't a claim that Mediterranean cooking is cheap: some of its best-known ingredients, from good olive oil to fresh fish, aren't. It's an argument for borrowing a handful of techniques that several of these traditions share.</p></section>
        <Section title="There is no single Mediterranean cuisine"><p>Greek, Italian, Lebanese, Spanish, Moroccan and Turkish cooking — to name just a few — are distinct culinary traditions with their own ingredients, history and character. Treating ‘Mediterranean food’ as one uniform, inexpensive cuisine flattens that variety. What's worth taking from these traditions isn't a claim about their overall cost, but a set of techniques that turn up across several of them.</p></Section>
        <Section title="Where the practical value comes from"><List><Item>Build a dinner around beans, lentils, grains and vegetables, rather than a large piece of meat or fish.</Item><Item>Use herbs, garlic, citrus, tomatoes and spices to bring flavour, rather than relying on the quantity of a costly ingredient.</Item><Item>Treat meat, fish or cheese as a smaller, supporting element where a dish calls for it.</Item><Item>Reuse bread, cooked grains, sauces and vegetables across more than one dinner.</Item></List><p>None of this is exclusive to the Mediterranean — similar techniques appear in low-cost cooking traditions worldwide — but it's a useful, well-documented set of examples to draw from.</p></Section>
        <Section title="Affordable ingredients that carry flavour well"><List><Item>Dried or tinned lentils, chickpeas and beans</Item><Item>Onions and garlic</Item><Item>Tinned tomatoes</Item><Item>Rice, pasta, bulgur wheat and couscous</Item><Item>Parsley, oregano, mint and bay</Item><Item>Cumin, paprika and cinnamon</Item><Item>Lemon</Item></List><p>These form the backbone of a satisfying dinner without needing a large quantity of any single expensive ingredient.</p></Section>
        <Section title="Ingredients that can make the checkout more expensive"><p>Good-quality extra virgin olive oil, fresh fish and seafood, pine nuts, almonds, saffron and speciality cheeses can all add significantly to a shopping bill. They can still have a place — used in small quantities, saved for when you want to spend a little more, or swapped for a more accessible alternative.</p></Section>
        <Section title="Four appetising dinner examples">
          <section><h3 className="font-bold text-dbd-ink">Greek fasolada</h3><p className="mt-2">A hearty white bean soup, one of the best-known bean dishes in Greek cooking, made by simmering dried white beans with onion, carrot, celery and tomato, finished with a generous amount of olive oil. It's traditionally meat-free.</p></section>
          <section><h3 className="font-bold text-dbd-ink">Roman pasta e ceci</h3><p className="mt-2">A central and southern Italian dish of small pasta and chickpeas, simmered in a tomato-and-rosemary broth with garlic. The chickpea-and-pasta base needs no meat, although some Roman versions include anchovy.</p></section>
          <section><h3 className="font-bold text-dbd-ink">Lebanese mujadara</h3><p className="mt-2">A Levantine dish of lentils and rice, or bulgur wheat, built almost entirely around deeply caramelised onions, with cumin as the main spice. The version described here contains no animal-derived ingredients; check stock, packaged ingredients and accompaniments. It's found across Lebanon, Jordan and Syria.</p></section>
          <section><h3 className="font-bold text-dbd-ink">Spanish lentejas con chorizo</h3><p className="mt-2">A Spanish lentil stew with potato, carrot, onion, garlic and paprika, where a small amount of chorizo is sliced in to flavour the whole pot rather than serving as the main component.</p></section>
        </Section>
        <Section title="Reusing ingredients across several dinners"><p>A larger pot of cooked lentils, chickpeas or rice can be split across two or three dinners. A batch of caramelised onions can flavour a grain, a stew or a simple bean dish. A tomato-and-garlic base can work beneath pasta e ceci one night and a different bean or vegetable dinner later on.</p></Section>
        <ProgrammaticDisclosureList items={MEDITERRANEAN_STORAGE_DISCLOSURES} className="mt-6" />
        <Section title="UK-supermarket substitutions and how they alter the result"><List><Item>Tinned lentils or chickpeas are already cooked, so they can be drained and added without soaking, in place of dried.</Item><Item>Use a more everyday cooking oil in place of extra virgin olive oil for cooking; keep a small amount of good olive oil for a finishing drizzle if you want its characteristic flavour.</Item><Item>Widely available cooking chorizo can replace a specific artisan variety, although the exact taste and texture vary by brand.</Item><Item>A more everyday hard cheese can replace Parmesan or Pecorino for grating, changing the flavour while still adding a savoury, salty finish.</Item><Item>A widely available long-grain rice may replace a specific variety, but follow the pack instructions because texture, liquid requirements and cooking time can differ.</Item></List><p>These substitutions change the character of a dish rather than its core structure, so try the closest available alternative rather than skipping the ingredient's role entirely.</p></Section>
        <ProgrammaticDisclosureList items={MEDITERRANEAN_PRODUCT_DISCLOSURES} className="mt-6" />
        <Section title="Frequently asked questions">{guide.faqs.map(faq => <section key={faq.question}><h3 className="font-bold text-dbd-ink">{faq.question}</h3><p className="mt-2">{faq.answer}</p></section>)}</Section>
        <Section title="How DinnerByDesign can help"><p>Search DinnerByDesign for dinners built around beans, lentils and grains, and use the Low Cost filter alongside these techniques. Plan my week can help you schedule dinners that reuse a base sauce, cooked grain or batch of caramelised onions across more than one night.</p></Section>
        <Section title="Sources and further reading" className="border-t border-dbd-rule/50 pt-8"><p>The Spanish example uses a preparation reference rather than an official cultural authority and is therefore described in deliberately general terms.</p><ul className="space-y-3 text-sm leading-6">{guide.sources.map(source => <li key={source.url}><SourceLink href={source.url}>{source.label}</SourceLink></li>)}</ul></Section>
        <ProgrammaticDisclosureList items={MEDITERRANEAN_SOURCE_DISCLOSURES} className="mt-6" />
        <Section title="Related guidance"><p><a href="/food-costs/ways-to-reduce-grocery-costs" className="font-semibold text-dbd-accent hover:underline">Explore practical ways to manage grocery costs</a>, <a href="/food-costs/portion-planning-and-food-waste" className="font-semibold text-dbd-accent hover:underline">plan portions and reduce waste</a>, <a href="/food-safety" className="font-semibold text-dbd-accent hover:underline">review food-safety guidance</a> or <a href="/recipe-methodology" className="font-semibold text-dbd-accent hover:underline">read how dinners are selected</a>.</p></Section>
      </article>
      <ProgrammaticDisclosureFooter copy={MEDITERRANEAN_DISCLOSURE_FOOTER} className="mt-10" />
      <section className="mt-10 rounded bg-dbd-ink p-6 text-white sm:flex sm:items-center sm:justify-between sm:gap-6"><div><h2 className="text-xl font-bold">Make affordable ingredients taste good</h2><p className="mt-2 text-sm leading-6 text-white/70">Find suitable dinners and plan ingredients across your week.</p></div><button type="button" onClick={onPlanWeek} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-white px-5 text-sm font-bold text-dbd-ink sm:mt-0 sm:w-auto">Plan my week <ArrowRight size={16} /></button></section>
    </main>
  </div>
);
