import React from 'react';
import { Wordmark } from '../Wordmark';
import { ArrowRight } from 'lucide-react';
import { OFFAL_BUDGET_GUIDE as guide } from '../../content/seoFoodCostGuides';
import { OFFAL_BUDGET_DISCLOSURE_FOOTER, OFFAL_PRICE_DISCLOSURES, OFFAL_SAFETY_DISCLOSURES } from '../../content/programmaticDisclosures';
import { ProgrammaticDisclosureFooter, ProgrammaticDisclosureList } from '../ProgrammaticDisclosures';

const Section: React.FC<{ title: string; children: React.ReactNode; className?: string }> = ({ title, children, className = '' }) => <section className={`mt-10 ${className}`}><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-dbd-ink-3">{children}</div></section>;
const List: React.FC<{ children: React.ReactNode }> = ({ children }) => <ul className="space-y-3">{children}</ul>;
const Item: React.FC<{ children: React.ReactNode }> = ({ children }) => <li className="flex gap-3"><span aria-hidden="true" className="text-dbd-accent">—</span><span>{children}</span></li>;

export const OffalBudgetGuideView: React.FC<{ onFindDinners: () => void }> = ({ onFindDinners }) => (
  <div className="min-h-screen bg-[#faf9f7] text-dbd-ink">
    <header className="border-b border-dbd-rule/50 bg-dbd-surface"><div className="mx-auto flex min-h-[82px] max-w-5xl items-center justify-between px-4 sm:min-h-[96px]"><a href="/" aria-label="DinnerByDesign home"><Wordmark className="text-[34.2px] sm:text-[39.6px]" /></a><a href="/signin?mode=signin" className="text-xs font-bold text-dbd-accent hover:underline">Sign in</a></div></header>
    <main className="mx-auto max-w-3xl px-4 py-8 pb-20 sm:py-12">
      <nav aria-label="Breadcrumb" className="text-xs text-dbd-ink-3"><a href="/" className="hover:underline">DinnerByDesign</a><span className="px-2">/</span><span>Food cost guides</span></nav>
      <article>
        <header className="mt-7"><p className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-dbd-accent">Food cost guide</p><h1 className="mt-2 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{guide.title}</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-dbd-ink-3">{guide.description}</p><p className="mt-3 text-xs text-dbd-ink-3">By {guide.editorialOwner} · Published 20 July 2026 · Last reviewed 20 July 2026</p></header>
        <section className="mt-8 border-y border-dbd-rule/50 py-6 text-[15px] leading-7 text-dbd-ink-3"><p>Liver, kidney and heart can cost less than more familiar cuts, but they are not direct substitutes. Each brings its own flavour, texture and cooking requirement. Used thoughtfully — with onions, vegetables, grains, pulses and assertive seasonings — they can produce satisfying, characterful dinners without relying on a large quantity of meat.</p></section>
        <Section title="Why consider offal?"><p>Offal gives you a way to bring meat into a dinner as a smaller, supporting element rather than the centrepiece — similar in principle to using a little bacon or a spoonful of mince to flavour a larger dish of beans or grains. It is one option among several for managing ingredient spending, not something any household needs to adopt. If the flavour and preparation suit you, it is worth trying; if not, our low-cost cooking guide covers the same ground with more familiar ingredients.</p></Section>
        <Section title="Is it necessarily less expensive?"><p>Often, but not always. Offal can be less expensive per kilogram than familiar cuts, but the current shelf price, pack size and usable quantity all matter.</p><p><strong className="text-dbd-ink">Price snapshot, 20 July 2026:</strong> Tesco listed lamb liver at £6.15/kg, lamb heart at £7.30/kg and lamb kidney at £8.00/kg, compared with lamb mince from £13.00/kg. Prices, ranges and availability change, so check the current shelf price.</p><ProgrammaticDisclosureList items={OFFAL_PRICE_DISCLOSURES} className="mt-6" /></Section>
        <Section title="Liver, kidney and heart: how they differ"><List><Item><strong className="text-dbd-ink">Liver:</strong> soft in texture, with a flavour ranging from mild to rich. Thin, evenly sized pieces cook through quickly.</Item><Item><strong className="text-dbd-ink">Kidney:</strong> firmer, with a distinct mineral flavour. It usually needs its white core trimmed and can suit quick or slow cooking depending on the type and recipe.</Item><Item><strong className="text-dbd-ink">Heart:</strong> denser and leaner, closer to a muscle cut. Cook it long and slow, or slice it thinly for quick cooking.</Item></List></Section>
        <Section title="Flavours that work well with each"><List><Item><strong className="text-dbd-ink">Liver:</strong> onions, sage, mustard, vinegar or sherry.</Item><Item><strong className="text-dbd-ink">Kidney:</strong> mustard, Worcestershire sauce, paprika, stock or ale in a pie or stew.</Item><Item><strong className="text-dbd-ink">Heart:</strong> garlic, chilli, citrus or a vinegar-based marinade.</Item></List></Section>
        <Section title="How to prevent tough or dry results while still cooking safely"><p>Liver cooks quickly, so remove it from the heat once it is thoroughly cooked. Heart works at either end of the scale — thinly sliced and cooked quickly, or left whole and cooked low and slow. Kidney can suit quick or slow cooking depending on the type and preparation. Follow a recipe written for the specific offal.</p><ProgrammaticDisclosureList items={OFFAL_SAFETY_DISCLOSURES} className="mt-6" /></Section>
        <Section title="Three approachable starting points"><List><Item>Thoroughly cooked lamb liver with onions, mustard and vinegar.</Item><Item>Kidney with root vegetables in a rich gravy.</Item><Item>Slow-cooked heart with garlic, smoked paprika and tomatoes.</Item></List></Section>
        <Section title="Availability in supermarkets and butchers"><p>Liver and kidney are stocked fairly reliably in the fresh meat aisle of major UK supermarkets. Heart, tongue and tripe are less consistent. A local butcher may be able to source and prepare them, so check before travelling.</p></Section>
        <Section title="Vitamin A, pregnancy and food-safety guidance"><p>The NHS advises against eating liver or liver products such as pâté more than once a week. Liver and liver products should be avoided during pregnancy. If you regularly eat liver or take supplements containing vitamin A, read the current NHS guidance linked below.</p></Section>
        <Section title="Frequently asked questions">{guide.faqs.map(faq => <section key={faq.question}><h3 className="font-bold text-dbd-ink">{faq.question}</h3><p className="mt-2">{faq.answer}</p></section>)}</Section>
        <Section title="Find offal dinners and products"><p>Search DinnerByDesign for liver, kidney, heart and other offal options, then compare suitable dinners and ready-made products in one place.</p></Section>
        <Section title="Sources and further reading" className="border-t border-dbd-rule/50 pt-8"><p>Guidance and prices reviewed 20 July 2026.</p><ul className="space-y-3 text-sm leading-6">{guide.sources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer" className="font-semibold text-dbd-accent hover:underline">{source.label}</a></li>)}</ul></Section>
        <Section title="Related guidance"><p><a href="/food-costs/ways-to-reduce-grocery-costs" className="font-semibold text-dbd-accent hover:underline">Explore practical ways to manage grocery costs</a>, <a href="/pricing-methodology" className="font-semibold text-dbd-accent hover:underline">read the pricing methodology</a>, <a href="/food-safety" className="font-semibold text-dbd-accent hover:underline">review food-safety guidance</a> or <a href="/recipe-methodology" className="font-semibold text-dbd-accent hover:underline">read how dinners are selected</a>.</p></Section>
      </article>
      <ProgrammaticDisclosureFooter copy={OFFAL_BUDGET_DISCLOSURE_FOOTER} className="mt-10" />
      <section className="mt-10 rounded bg-dbd-ink p-6 text-white sm:flex sm:items-center sm:justify-between sm:gap-6"><div><h2 className="text-xl font-bold">Find suitable offal options</h2><p className="mt-2 text-sm leading-6 text-white/70">Search directly or include offal in your personalised suggestions.</p></div><button type="button" onClick={onFindDinners} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-white px-5 text-sm font-bold text-dbd-ink sm:mt-0 sm:w-auto">Find offal dinners <ArrowRight size={16} /></button></section>
    </main>
  </div>
);
