import React from 'react';
import { ArrowRight } from 'lucide-react';
import { PORTION_PLANNING_GUIDE as guide } from '../../content/seoFoodCostGuides';
import { PORTION_PLANNING_DISCLOSURE_FOOTER, PORTION_PLANNING_DISCLOSURES } from '../../content/programmaticDisclosures';
import { ProgrammaticDisclosureFooter, ProgrammaticDisclosureList } from '../ProgrammaticDisclosures';

const Section: React.FC<{ title: string; children: React.ReactNode; className?: string }> = ({ title, children, className = '' }) => <section className={`mt-10 ${className}`}><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-dbd-ink-3">{children}</div></section>;
const List: React.FC<{ children: React.ReactNode }> = ({ children }) => <ul className="space-y-3">{children}</ul>;
const Item: React.FC<{ children: React.ReactNode }> = ({ children }) => <li className="flex gap-3"><span aria-hidden="true" className="text-dbd-accent">—</span><span>{children}</span></li>;

export const PortionPlanningGuideView: React.FC<{ onPlanWeek: () => void }> = ({ onPlanWeek }) => (
  <div className="min-h-screen bg-[#faf9f7] text-dbd-ink">
    <header className="border-b border-dbd-rule/50 bg-dbd-surface"><div className="mx-auto flex min-h-[82px] max-w-5xl items-center justify-between px-4 sm:min-h-[96px]"><a href="/" aria-label="DinnerByDesign home"><img src="/dbd-logo-with-pin.png" alt="DinnerByDesign" className="h-[34.2px] w-auto max-w-[207px] object-contain mix-blend-multiply sm:h-[39.6px]" /></a><a href="/signin?mode=signin" className="text-xs font-bold text-dbd-accent hover:underline">Sign in</a></div></header>
    <main className="mx-auto max-w-3xl px-4 py-8 pb-20 sm:py-12">
      <nav aria-label="Breadcrumb" className="text-xs text-dbd-ink-3"><a href="/" className="hover:underline">DinnerByDesign</a><span className="px-2">/</span><span>Food cost guides</span></nav>
      <article>
        <header className="mt-7"><p className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-dbd-accent">Food cost guide</p><h1 className="mt-2 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{guide.title}</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-dbd-ink-3">{guide.description}</p><p className="mt-3 text-xs text-dbd-ink-3">By {guide.editorialOwner} · Published 20 July 2026 · Last reviewed 20 July 2026</p></header>
        <section className="mt-8 border-y border-dbd-rule/50 py-6 text-[15px] leading-7 text-dbd-ink-3"><p>It is easy to assume that cooking more is generous and cooking less saves money. In practice, the two do not always match up. Cooking too much of an expensive ingredient can quietly push up what a dinner actually costs to make, while serving smaller portions does not automatically bring down what you pay at the supermarket — because much of what you buy comes in a fixed pack, not a made-to-order amount. Getting the most from your ingredients means paying attention to both: how much you serve, and how the whole pack gets used.</p></section>
        <Section title="Portion planning, not portion control"><p>Portion planning is different from portion control. It is not about eating less — it is about deciding, before you cook, how many people a dinner is meant to serve, and whether any extra portions have a specific purpose. A dinner planned for four, cooked for four, with nothing left over, is portion planning. So is a dinner deliberately cooked for six, with two portions set aside for tomorrow’s lunch. What it avoids is the quiet drift into cooking an unconsidered amount — too much to eat, too little to be worth saving properly, and likely to end up thrown away.</p></Section>
        <Section title="Where portion planning makes the greatest difference"><p>Portion planning has the biggest effect on the ingredients that cost the most — meat, fish and cheese in particular. A dinner built mostly around vegetables, pulses, grains, potatoes and a well-flavoured sauce can be just as satisfying with a smaller quantity of the priciest ingredient, because the volume, texture and flavour come from elsewhere on the plate.</p></Section>
        <Section title="Why checkout costs do not always fall"><p>Supermarkets sell many ingredients in fixed pack sizes, not the exact amount a recipe calls for. If a dinner needs 300g of mince and the smallest pack available is 500g, buying less is not an option — the full pack has to be bought regardless of how much ends up in the pan.</p><p>Keep two figures separate: the value of the ingredients actually used in a dinner, and the cost of the complete packs bought to get them. Reducing quantities can reduce the first without changing the second. The unused part of the pack only provides further value when it is used in another dinner or stored safely for later.</p></Section>
        <Section title="When cooking extra is economical"><p>Cooking more than one dinner’s worth is not a problem when the extra is accounted for. A larger batch of rice, a bigger pot of tomato-based sauce or an extra portion of chicken can turn a fixed pack size into an advantage when it has a planned destination — tomorrow’s lunch, the freezer or another dinner later in the week.</p></Section>
        <Section title="How to plan portions realistically"><p>Realistic portions depend on who you are feeding, their appetite and what else is being served. A dinner accompanied by bread, rice, vegetables or a substantial salad may need less of its main component than one served alone.</p><p>A household of two cooking a recipe written for four can halve the recipe, or cook the full amount with the extra earmarked for another dinner. Cooking without deciding what will happen to the extra can easily lead to avoidable waste.</p></Section>
        <ProgrammaticDisclosureList items={PORTION_PLANNING_DISCLOSURES} className="mt-6" />
        <Section title="Practical ways to reduce waste"><List><Item>Weigh or measure the more expensive ingredients — meat, fish and cheese in particular — rather than guessing.</Item><Item>Divide large packs into usable portions as soon as you get home.</Item><Item>Freeze suitable surplus promptly and label leftovers with the date.</Item><Item>Schedule ingredients across two or three dinners rather than buying separately for each one.</Item></List></Section>
        <Section title="Keeping lower-cost dinners satisfying"><p>None of this needs to mean smaller, blander dinners. A smaller quantity of chicken stretches further shredded through a spiced rice dish with herbs and lime than served plain in a larger piece. A modest amount of strong cheese, grated rather than sliced, can carry a gratin. Pulses and grains take on bold flavours from curry paste, harissa or toasted spices, with meat, fish or cheese adding character rather than bulk.</p><p>A useful test is whether a dinner would still feel complete with the expensive ingredient left out. If the sauce, spicing and other ingredients are doing most of the work, there may be room to serve less of it without the dinner feeling thin.</p></Section>
        <Section title="How DinnerByDesign helps"><p>DinnerByDesign lets you set the number of servings and see an estimated cost per portion before you shop. Cost per portion reflects the value of ingredients used; checkout cost may be higher because complete packs usually have to be bought. Build a week that deliberately reuses ingredients and generate a shopping list from the dinners you schedule.</p></Section>
        <Section title="Frequently asked questions">{guide.faqs.map(faq => <section key={faq.question}><h3 className="font-bold text-dbd-ink">{faq.question}</h3><p className="mt-2">{faq.answer}</p></section>)}</Section>
        <Section title="Making portion planning work"><p>Portion planning works best as part of a bigger picture: realistic serving sizes, awareness of what a pack size commits you to, planned leftovers and a week of dinners that share ingredients rather than each starting from scratch. It does not require eating less to spend less — it is about making sure everything you buy gets used well.</p></Section>
        <Section title="Sources and further reading" className="border-t border-dbd-rule/50 pt-8"><p>Guidance reviewed 20 July 2026.</p><ul className="space-y-3 text-sm leading-6">{guide.sources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer" className="font-semibold text-dbd-accent hover:underline">{source.label}</a></li>)}</ul></Section>
        <Section title="Related guidance"><p><a href="/food-costs/cooking-for-one-without-waste" className="font-semibold text-dbd-accent hover:underline">Plan dinners for one without waste</a>, <a href="/food-costs/low-cost-cooking-techniques" className="font-semibold text-dbd-accent hover:underline">explore low-cost cooking techniques</a>, <a href="/food-costs/batch-cooking-on-a-budget" className="font-semibold text-dbd-accent hover:underline">learn when batch cooking can save money</a>, <a href="/pricing-methodology" className="font-semibold text-dbd-accent hover:underline">read the pricing methodology</a> or <a href="/food-safety" className="font-semibold text-dbd-accent hover:underline">review food-safety guidance</a>.</p></Section>
      </article>
      <ProgrammaticDisclosureFooter copy={PORTION_PLANNING_DISCLOSURE_FOOTER} className="mt-10" />
      <section className="mt-10 rounded bg-dbd-ink p-6 text-white sm:flex sm:items-center sm:justify-between sm:gap-6"><div><h2 className="text-xl font-bold">Plan portions across your week</h2><p className="mt-2 text-sm leading-6 text-white/70">Set servings, coordinate ingredients and create a shopping list from scheduled dinners.</p></div><button type="button" onClick={onPlanWeek} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-white px-5 text-sm font-bold text-dbd-ink sm:mt-0 sm:w-auto">Plan my week <ArrowRight size={16} /></button></section>
    </main>
  </div>
);
