import React from 'react';
import { ArrowRight } from 'lucide-react';
import { SUMMER_STEWS_GUIDE as guide } from '../../content/seoFoodCostGuides';
import { SUMMER_STEWS_DISCLOSURE_FOOTER, SUMMER_STEWS_DISCLOSURES } from '../../content/programmaticDisclosures';
import { ProgrammaticDisclosureFooter, ProgrammaticDisclosureList } from '../ProgrammaticDisclosures';

const Section: React.FC<{ title: string; children: React.ReactNode; className?: string }> = ({ title, children, className = '' }) => (
  <section className={`mt-10 ${className}`}><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-dbd-ink-3">{children}</div></section>
);
const List: React.FC<{ children: React.ReactNode }> = ({ children }) => <ul className="space-y-3">{children}</ul>;
const Item: React.FC<{ children: React.ReactNode }> = ({ children }) => <li className="flex gap-3"><span aria-hidden="true" className="text-dbd-accent">—</span><span>{children}</span></li>;
const SourceLink: React.FC<{ href: string; children: React.ReactNode }> = ({ href, children }) => <a href={href} target="_blank" rel="noreferrer" className="font-semibold text-dbd-accent hover:underline">{children}</a>;

export const SummerStewsGuideView: React.FC<{ onPlanWeek: () => void }> = ({ onPlanWeek }) => (
  <div className="min-h-screen bg-[#faf9f7] text-dbd-ink">
    <header className="border-b border-dbd-rule/50 bg-dbd-surface"><div className="mx-auto flex min-h-[82px] max-w-5xl items-center justify-between px-4 sm:min-h-[96px]"><a href="/" aria-label="DinnerByDesign home"><img src="/dbd-logo-with-pin.png" alt="DinnerByDesign" className="h-[38px] w-auto max-w-[230px] object-contain mix-blend-multiply sm:h-[44px]" /></a><a href="/signin?mode=signin" className="text-xs font-bold text-dbd-accent hover:underline">Sign in</a></div></header>
    <main className="mx-auto max-w-3xl px-4 py-8 pb-20 sm:py-12">
      <nav aria-label="Breadcrumb" className="text-xs text-dbd-ink-3"><a href="/" className="hover:underline">DinnerByDesign</a><span className="px-2">/</span><span>Food cost guides</span></nav>
      <article>
        <header className="mt-7"><p className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-dbd-accent">Food cost guide</p><h1 className="mt-2 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{guide.title}</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-dbd-ink-3">{guide.description}</p><p className="mt-3 text-xs text-dbd-ink-3">By {guide.editorialOwner} · Published 20 July 2026 · Last reviewed 20 July 2026</p></header>
        <section className="mt-8 space-y-4 border-y border-dbd-rule/50 py-6 text-[15px] leading-7 text-dbd-ink-3">
          <p>A summer stew is generally lighter and quicker-cooking than a winter stew, built on fresh vegetables, herbs and a lighter broth or tomato base. Ingredients go in at different stages so each one keeps an appropriate texture, rather than everything cooking down together for hours.</p>
          <p>The financial case for cooking this way isn&apos;t that summer vegetables are automatically cheap — prices and availability still vary through the season and by retailer. It&apos;s that a stew built this way is unusually good at absorbing whatever you actually have that remains safe to eat: whichever vegetables are good value that week, or already sitting in the fridge needing to be used.</p>
        </section>
        <Section title="Where the practical value comes from"><List><Item>It accommodates whichever vegetables are currently good value or already need using, provided they remain safe to eat.</Item><Item>It combines vegetables with beans, lentils or grains, rather than relying on a large quantity of meat.</Item><Item>One tomato base, bunch of herbs or pack of vegetables can be used across several dinners.</Item><Item>Irregular quantities and surplus vegetables — the half pepper, the last two courgettes — become an intentional part of the dish rather than loose ends to work around.</Item><Item>It accepts substitutions without needing a completely different recipe.</Item><Item>It can be served with bread, rice or another inexpensive accompaniment when you want more volume.</Item></List></Section>
        <Section title="Staging vegetables by cooking time"><p>The main technique worth knowing is that not everything needs to go into the pot at once. Onions and firmer vegetables — peppers, aubergine, carrots — go in first and cook down into the base. Courgette, leafy vegetables and other more delicate ingredients go in later, so they retain their colour, texture and freshness rather than turning soft and grey. Herbs, and any final squeeze of lemon, go in right at the end, off the heat or close to it.</p><p>This isn&apos;t a rigid rule — some dinners benefit from everything cooking down together, and that&apos;s a reasonable choice too. Staging is simply a way to keep more texture and colour in the finished dish, if that&apos;s what you want from it.</p></Section>
        <Section title="Three flexible dinner ideas">
          <p>These are presented as adaptable starting points rather than named traditional dishes — change the vegetables to whatever you have, and treat the quantities as a guide rather than a fixed recipe.</p>
          <section><h3 className="font-bold text-dbd-ink">Tomato, courgette and butter bean stew with lemon and basil</h3><p className="mt-2">Onion and garlic cooked down first with tinned tomatoes, then butter beans warmed through, courgette added in the last few minutes so it keeps some bite, finished with lemon juice and torn basil off the heat.</p></section>
          <section><h3 className="font-bold text-dbd-ink">Chicken, pepper and sweetcorn broth with smoked paprika</h3><p className="mt-2">A light broth built from onion, pepper and smoked paprika, with a modest amount of chicken added to flavour rather than fill the bowl, and sweetcorn stirred in towards the end so it stays sweet and crisp. Cook the chicken thoroughly until steaming hot throughout, with no pink meat remaining.</p></section>
          <section><h3 className="font-bold text-dbd-ink">Aubergine, chickpea and tomato stew finished with fresh herbs</h3><p className="mt-2">Aubergine cooked down with onion and garlic until soft, chickpeas added to warm through, tinned tomatoes providing the base, and a handful of fresh parsley or coriander stirred in just before serving.</p></section>
        </Section>
        <Section title="Reusing a base across several dinners"><p>A larger batch of the onion-and-tomato base from any of these can do more than one job: it&apos;s the start of tonight&apos;s stew, but it can just as easily go under some pasta, alongside a piece of fish, or into a bean dish later in the week. The same applies to a bunch of herbs or a pack of vegetables bought for one dinner — splitting it across two dinners in the same week is usually more useful than trying to use all of it in one sitting.</p></Section>
        <Section title="Serving for extra volume"><p>Bread, rice, couscous or another inexpensive accompaniment is a straightforward way to add volume to a lighter stew without adding more of the more expensive ingredients. A smaller pot of stew served over rice, or with a thick slice of bread on the side, often goes further than the same stew served alone.</p></Section>
        <Section title="Food safety for cooked stews"><p>These dishes can be eaten warm or a little cooler, but that shouldn&apos;t be confused with leaving a cooked stew out at room temperature for an extended period. Current Food Standards Agency guidance is to cool cooked food and refrigerate it within two hours, eat refrigerated leftovers within 48 hours or freeze them, and reheat only once, until steaming hot all the way through.</p></Section>
        <ProgrammaticDisclosureList items={SUMMER_STEWS_DISCLOSURES} className="mt-6" />
        <Section title="Frequently asked questions">{guide.faqs.map(faq => <section key={faq.question}><h3 className="font-bold text-dbd-ink">{faq.question}</h3><p className="mt-2">{faq.answer}</p></section>)}</Section>
        <Section title="How DinnerByDesign can help"><p>Search DinnerByDesign for dinners that flex around whatever vegetables you have, and use the Low Cost filter alongside these techniques. Plan my week can help schedule a base sauce, herb bunch or vegetable pack across more than one dinner, and our <a href="/food-costs/low-cost-cooking-techniques" className="font-semibold text-dbd-accent hover:underline">low-cost cooking techniques</a> and <a href="/food-costs/portion-planning-and-food-waste" className="font-semibold text-dbd-accent hover:underline">portion-planning guides</a> cover the wider principles in more detail.</p></Section>
        <Section title="Sources and further reading" className="border-t border-dbd-rule/50 pt-8"><ul className="space-y-3 text-sm leading-6">{guide.sources.map(source => <li key={source.url}><SourceLink href={source.url}>{source.label}</SourceLink></li>)}</ul></Section>
        <Section title="Related guidance"><p><a href="/food-costs/low-cost-cooking-techniques" className="font-semibold text-dbd-accent hover:underline">Explore low-cost cooking techniques</a>, <a href="/food-costs/portion-planning-and-food-waste" className="font-semibold text-dbd-accent hover:underline">plan portions and reduce waste</a>, <a href="/food-costs/fresh-or-frozen" className="font-semibold text-dbd-accent hover:underline">choose between fresh and frozen produce</a>, <a href="/food-safety" className="font-semibold text-dbd-accent hover:underline">review food-safety guidance</a> or <a href="/recipe-methodology" className="font-semibold text-dbd-accent hover:underline">read how dinners are selected</a>.</p></Section>
      </article>
      <ProgrammaticDisclosureFooter copy={SUMMER_STEWS_DISCLOSURE_FOOTER} className="mt-10" />
      <section className="mt-10 rounded bg-dbd-ink p-6 text-white sm:flex sm:items-center sm:justify-between sm:gap-6"><div><h2 className="text-xl font-bold">Make vegetables work harder across your week</h2><p className="mt-2 text-sm leading-6 text-white/70">Find suitable dinners and plan shared ingredients with DinnerByDesign.</p></div><button type="button" onClick={onPlanWeek} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-white px-5 text-sm font-bold text-dbd-ink sm:mt-0 sm:w-auto">Plan my week <ArrowRight size={16} /></button></section>
    </main>
  </div>
);
